name: 2stupids
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "space_after_headers", "superscript", "with_toc_data"]
