name: Wind in the Wild
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks",
               "autolink",
               "strikethrough",
               "space_after_headers"]
exclude: [vendor]
